spring:
   datasource:
      url: dbc:mysql://localhost:3306/cricket_database
      username: ${MYSQL_USER}
      password: ${MYSQL_PASSWORD}
      driver-class-name: com.mysql.jdbc.Driver
   jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
server:
  port: 8092


