name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    services: 
      mysql:   
        image: mysql:5.5
        env: 
          MYSQL_DATABASE: cricket_database
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: test
          MYSQL_PASSWORD: test
     
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: run script file
      run: source ./project.sh
    - name: Build with Maven
      run: mvn package --file pom.xml
